version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:5000" 
    environment:
      DB_HOST: db                
      DB_USER: postgres           
      DB_NAME: recipe_db          
      DB_PASSWORD: 1761           
      DB_PORT: 5432               
    depends_on:
      - db
    volumes:
      - .:/usr/src/app            # Mounts the project directory to the container
      - /usr/src/app/node_modules # Ensures node_modules aren't overwritten by the bind mount

  db:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1761
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  pgdata:
